### ISSUE TITLE
Reupload schematic

### ISSUE THREAD

**Issue by alex2501** [strid3r21/BeeMotionS3#1]
Hi,
first of all, thank you very much for sharing your designs, really helped me a lot on mine.
Could you please reupload the schematic picture, because resolution is so bad I can read values of resistors for usb sensing.

Many thanks in advance.

Best regards,
Alex

**Comment by strid3r21** [comment]
hi, I've uploaded the PDF of the schematic that you can download and zoom around on to view the details easier.
